---

name: Run Python ruff linter
runs:
  using: composite
  steps:
    - name: Ruff
      uses: chartboost/ruff-action@v1
      with:
        version: 0.0.270
        args: --line-length=120 --target-version=py38
